using System.Globalization;

namespace VictusModeSwitch;

internal sealed class Localizer
{
    public Localizer(string? requestedLanguage)
    {
        RequestedLanguage = NormalizeRequestedLanguage(requestedLanguage);
        Language = RequestedLanguage == "system" ? GetSystemLanguage() : RequestedLanguage;
    }

    public string RequestedLanguage { get; }
    public string Language { get; }
    public string this[string key] => Translate(Language, key);
    public string Format(string key, params object[] values) => string.Format(this[key], values);

    public string ModeName(AppMode mode) => this[mode switch
    {
        AppMode.Eco => "ModeEco",
        AppMode.Performance => "ModePerformance",
        _ => "ModeStandard"
    }];

    public string ModeDescription(AppMode mode) => this[mode switch
    {
        AppMode.Eco => "ModeEcoDescription",
        AppMode.Performance => "ModePerformanceDescription",
        _ => "ModeStandardDescription"
    }];

    public IReadOnlyList<LanguageOption> GetLanguageOptions() => new[]
    {
        new LanguageOption("system", this["LanguageSystem"]),
        new LanguageOption("ru", "Русский"),
        new LanguageOption("uk", "Українська"),
        new LanguageOption("en", "English")
    };

    private static string NormalizeRequestedLanguage(string? language) => language?.ToLowerInvariant() switch
    {
        "ru" => "ru",
        "uk" => "uk",
        "en" => "en",
        _ => "system"
    };

    private static string GetSystemLanguage() => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName switch
    {
        "ru" => "ru",
        "uk" => "uk",
        _ => "en"
    };

    private static string Translate(string language, string key) => language switch
    {
        "ru" => Russian(key),
        "uk" => Ukrainian(key),
        _ => English(key)
    };

    private static string Russian(string key) => key switch
    {
        "ModeEco" => "Eco",
        "ModeStandard" => "Стандартный",
        "ModePerformance" => "Performance",
        "ModeEcoDescription" => "Прохладный профиль BIOS и экономия энергии",
        "ModeStandardDescription" => "Сбалансированный тепловой профиль HP",
        "ModePerformanceDescription" => "Максимальный тепловой профиль HP",
        "MaxFan" => "Максимальные вентиляторы",
        "MaxFanOn" => "Max Fan включён",
        "MaxFanOff" => "Max Fan выключен",
        "MaxFanOnDescription" => "Вентиляторы работают на максимальной скорости",
        "MaxFanOffDescription" => "Автоматическое управление вентиляторами",
        "Settings" => "Настройки",
        "CheckUpdates" => "Проверить обновления",
        "OpenLog" => "Открыть журнал",
        "Exit" => "Выход",
        "ModeError" => "Не удалось переключить режим",
        "FanError" => "Не удалось переключить вентиляторы",
        "PartialMode" => "Режим включён частично. Подробности в журнале",
        "General" => "Основное",
        "Power" => "Питание",
        "About" => "О программе",
        "GeneralTitle" => "Основное",
        "GeneralSubtitle" => "Режимы, аппаратная кнопка, хоткей и уведомления",
        "QuickControls" => "Быстрое управление",
        "CurrentMode" => "Текущий режим",
        "ChangingMode" => "Применение режима...",
        "ChangingFan" => "Применение режима вентиляторов...",
        "ModeApplied" => "Режим применён",
        "FanDescription" => "Независимо включает максимальные обороты вентиляторов",
        "Language" => "Язык приложения",
        "LanguageSystem" => "Как в Windows",
        "LanguageDescription" => "По умолчанию используется язык интерфейса Windows",
        "Notifications" => "Уведомления о переключении",
        "NotificationsDescription" => "Показывать компактную плашку при использовании ромбика или хоткея",
        "KeyboardShortcut" => "Комбинация клавиш",
        "KeyboardShortcutDescription" => "Повторяет 1, 2 или 3 нажатия ромбика",
        "ShortcutNotAssigned" => "Не назначено",
        "RecordShortcut" => "Записать комбинацию",
        "PressShortcut" => "Нажмите сочетание...",
        "ShortcutNeedsModifier" => "Добавьте Ctrl / Alt / Shift / Win",
        "ClearShortcut" => "Удалить комбинацию",
        "ShortcutConflict" => "Это сочетание уже занято Windows или другой программой. Предыдущая комбинация сохранена.",
        "ShortcutRegistrationFailed" => "Windows не смогла зарегистрировать сочетание (ошибка {0}). Предыдущая комбинация сохранена.",
        "ShortcutStartupFailed" => "Настроенный хоткей занят и сейчас недоступен. Выберите другой в настройках.",
        "DiamondButton" => "Ромбик и комбинация клавиш",
        "DiamondDescription" => "Жесты определяются по быстрым последовательным нажатиям",
        "SinglePress" => "Одно нажатие",
        "DoublePress" => "Два нажатия",
        "TriplePress" => "Три нажатия",
        "ToggleModes" => "Стандартный ↔ Performance",
        "ToggleMaxFan" => "Max Fan вкл. / выкл.",
        "EnableEco" => "Включить Eco",
        "PowerTitle" => "Питание и Eco",
        "PowerSubtitle" => "Точная настройка энергосбережения",
        "EcoBehaviorTitle" => "Поведение Eco",
        "EcoRefreshRate" => "Ограничивать экран до 60 Гц",
        "EcoRefreshRateDescription" => "Только встроенный дисплей; исходная частота вернётся при выходе из Eco",
        "EcoFrameRate" => "Ограничивать NVIDIA до 60 FPS",
        "EcoFrameRateDescription" => "Глобальный лимит драйвера; более низкое исходное значение сохраняется",
        "EcoTurboBoost" => "Отключать Turbo Boost",
        "EcoTurboBoostDescription" => "Снижает пиковую мощность и нагрев процессора",
        "WindowsPowerTitle" => "Настройка Windows",
        "ApplyingEcoBehavior" => "Применение настроек Eco...",
        "EcoBehaviorApplied" => "Настройки Eco применены",
        "PowerTuning" => "Настраивать Windows вместе с режимом",
        "PowerTuningDescription" => "Ускоряет Windows в Performance и снижает расход энергии в Eco",
        "EcoAcLimit" => "Предел процессора Eco от сети",
        "EcoAcDescription" => "Максимальная производительность процессора при подключённом питании",
        "EcoBatteryLimit" => "Предел процессора Eco от батареи",
        "EcoBatteryDescription" => "Максимальная производительность процессора без зарядного устройства",
        "PowerRestoreNote" => "Eco-ограничения снимаются при выходе; настройки Windows возвращаются в Стандартном.",
        "AboutTitle" => "Victus Mode Switch",
        "AboutSubtitle" => "Лёгкий контроллер режимов для поддерживаемых HP Victus",
        "Version" => "Версия {0}",
        "SupportedHardware" => "Поддерживаемое устройство",
        "SupportedHardwareDescription" => "HP Victus 15-fa0020ua, системная плата 8A4F, Thermal Policy V0",
        "Updates" => "Обновления",
        "CheckForUpdates" => "Проверять обновления автоматически",
        "CheckForUpdatesDescription" => "Проверка GitHub Releases выполняется не чаще одного раза в сутки",
        "CheckNow" => "Проверить сейчас",
        "CheckingUpdate" => "Проверяем GitHub Releases...",
        "UpToDate" => "Установлена актуальная версия",
        "UpdateAvailable" => "Доступна версия {0}",
        "UpdateError" => "Не удалось проверить обновления",
        "OpenGitHub" => "Открыть проект на GitHub",
        "BuiltWithAi" => "Проект разработан при помощи искусственного интеллекта и проверен на одном ноутбуке.",
        "RiskNoticeTitle" => "Использование на свой риск",
        "RiskNotice" => "Программа обращается к недокументированному интерфейсу HP BIOS. Автор и участники не несут ответственности за повреждения, потерю данных или гарантийные последствия.",
        "UpdateReadyTitle" => "Доступно обновление",
        "UpdateReadyDescription" => "Victus Mode Switch {0} готов к установке.",
        "ReleaseNotes" => "Что изменилось",
        "InstallUpdate" => "Скачать и установить",
        "Later" => "Позже",
        "DownloadingUpdate" => "Загрузка установщика... {0}%",
        "VerifyingUpdate" => "Проверка SHA-256...",
        "UpdateFailed" => "Обновление не установлено: {0}",
        _ => English(key)
    };

    private static string Ukrainian(string key) => key switch
    {
        "ModeEco" => "Eco",
        "ModeStandard" => "Стандартний",
        "ModePerformance" => "Performance",
        "ModeEcoDescription" => "Прохолодний профіль BIOS та економія енергії",
        "ModeStandardDescription" => "Збалансований тепловий профіль HP",
        "ModePerformanceDescription" => "Максимальний тепловий профіль HP",
        "MaxFan" => "Максимальні вентилятори",
        "MaxFanOn" => "Max Fan увімкнено",
        "MaxFanOff" => "Max Fan вимкнено",
        "MaxFanOnDescription" => "Вентилятори працюють на максимальній швидкості",
        "MaxFanOffDescription" => "Автоматичне керування вентиляторами",
        "Settings" => "Налаштування",
        "CheckUpdates" => "Перевірити оновлення",
        "OpenLog" => "Відкрити журнал",
        "Exit" => "Вихід",
        "ModeError" => "Не вдалося перемкнути режим",
        "FanError" => "Не вдалося перемкнути вентилятори",
        "PartialMode" => "Режим застосовано частково. Подробиці в журналі",
        "General" => "Основне",
        "Power" => "Живлення",
        "About" => "Про програму",
        "GeneralTitle" => "Основне",
        "GeneralSubtitle" => "Режими, апаратна кнопка, хоткей та сповіщення",
        "QuickControls" => "Швидке керування",
        "CurrentMode" => "Поточний режим",
        "ChangingMode" => "Застосування режиму...",
        "ChangingFan" => "Застосування режиму вентиляторів...",
        "ModeApplied" => "Режим застосовано",
        "FanDescription" => "Незалежно вмикає максимальні оберти вентиляторів",
        "Language" => "Мова програми",
        "LanguageSystem" => "Як у Windows",
        "LanguageDescription" => "Типово використовується мова інтерфейсу Windows",
        "Notifications" => "Сповіщення про перемикання",
        "NotificationsDescription" => "Показувати компактне повідомлення під час використання ромбика або хоткея",
        "KeyboardShortcut" => "Комбінація клавіш",
        "KeyboardShortcutDescription" => "Повторює 1, 2 або 3 натискання ромбика",
        "ShortcutNotAssigned" => "Не призначено",
        "RecordShortcut" => "Записати комбінацію",
        "PressShortcut" => "Натисніть сполучення...",
        "ShortcutNeedsModifier" => "Додайте Ctrl / Alt / Shift / Win",
        "ClearShortcut" => "Видалити комбінацію",
        "ShortcutConflict" => "Це сполучення вже зайняте Windows або іншою програмою. Попередню комбінацію збережено.",
        "ShortcutRegistrationFailed" => "Windows не змогла зареєструвати сполучення (помилка {0}). Попередню комбінацію збережено.",
        "ShortcutStartupFailed" => "Налаштований хоткей зайнятий і зараз недоступний. Виберіть інший у налаштуваннях.",
        "DiamondButton" => "Ромбик і комбінація клавіш",
        "DiamondDescription" => "Жести визначаються за швидкими послідовними натисканнями",
        "SinglePress" => "Одне натискання",
        "DoublePress" => "Два натискання",
        "TriplePress" => "Три натискання",
        "ToggleModes" => "Стандартний ↔ Performance",
        "ToggleMaxFan" => "Max Fan увімк. / вимк.",
        "EnableEco" => "Увімкнути Eco",
        "PowerTitle" => "Живлення та Eco",
        "PowerSubtitle" => "Точне налаштування енергозбереження",
        "EcoBehaviorTitle" => "Поведінка Eco",
        "EcoRefreshRate" => "Обмежувати екран до 60 Гц",
        "EcoRefreshRateDescription" => "Лише вбудований дисплей; початкова частота повернеться після виходу з Eco",
        "EcoFrameRate" => "Обмежувати NVIDIA до 60 FPS",
        "EcoFrameRateDescription" => "Глобальний ліміт драйвера; нижче початкове значення зберігається",
        "EcoTurboBoost" => "Вимикати Turbo Boost",
        "EcoTurboBoostDescription" => "Знижує пікову потужність і нагрівання процесора",
        "WindowsPowerTitle" => "Налаштування Windows",
        "ApplyingEcoBehavior" => "Застосування налаштувань Eco...",
        "EcoBehaviorApplied" => "Налаштування Eco застосовано",
        "PowerTuning" => "Налаштовувати Windows разом із режимом",
        "PowerTuningDescription" => "Прискорює Windows у Performance та знижує витрати енергії в Eco",
        "EcoAcLimit" => "Межа процесора Eco від мережі",
        "EcoAcDescription" => "Максимальна продуктивність процесора з підключеним живленням",
        "EcoBatteryLimit" => "Межа процесора Eco від батареї",
        "EcoBatteryDescription" => "Максимальна продуктивність процесора без зарядного пристрою",
        "PowerRestoreNote" => "Eco-обмеження знімаються після виходу; налаштування Windows повертаються у Стандартному.",
        "AboutTitle" => "Victus Mode Switch",
        "AboutSubtitle" => "Легкий контролер режимів для підтримуваних HP Victus",
        "Version" => "Версія {0}",
        "SupportedHardware" => "Підтримуваний пристрій",
        "SupportedHardwareDescription" => "HP Victus 15-fa0020ua, системна плата 8A4F, Thermal Policy V0",
        "Updates" => "Оновлення",
        "CheckForUpdates" => "Перевіряти оновлення автоматично",
        "CheckForUpdatesDescription" => "Перевірка GitHub Releases виконується не частіше одного разу на добу",
        "CheckNow" => "Перевірити зараз",
        "CheckingUpdate" => "Перевіряємо GitHub Releases...",
        "UpToDate" => "Встановлено актуальну версію",
        "UpdateAvailable" => "Доступна версія {0}",
        "UpdateError" => "Не вдалося перевірити оновлення",
        "OpenGitHub" => "Відкрити проєкт на GitHub",
        "BuiltWithAi" => "Проєкт розроблено за допомогою штучного інтелекту та перевірено на одному ноутбуці.",
        "RiskNoticeTitle" => "Використання на власний ризик",
        "RiskNotice" => "Програма звертається до недокументованого інтерфейсу HP BIOS. Автор та учасники не відповідають за пошкодження, втрату даних або гарантійні наслідки.",
        "UpdateReadyTitle" => "Доступне оновлення",
        "UpdateReadyDescription" => "Victus Mode Switch {0} готовий до встановлення.",
        "ReleaseNotes" => "Що змінилося",
        "InstallUpdate" => "Завантажити й установити",
        "Later" => "Пізніше",
        "DownloadingUpdate" => "Завантаження інсталятора... {0}%",
        "VerifyingUpdate" => "Перевірка SHA-256...",
        "UpdateFailed" => "Оновлення не встановлено: {0}",
        _ => English(key)
    };

    private static string English(string key) => key switch
    {
        "ModeEco" => "Eco",
        "ModeStandard" => "Standard",
        "ModePerformance" => "Performance",
        "ModeEcoDescription" => "Cooler BIOS profile and lower power use",
        "ModeStandardDescription" => "Balanced HP thermal profile",
        "ModePerformanceDescription" => "Maximum HP thermal profile",
        "MaxFan" => "Maximum fan speed",
        "MaxFanOn" => "Max Fan on",
        "MaxFanOff" => "Max Fan off",
        "MaxFanOnDescription" => "Fans are running at maximum speed",
        "MaxFanOffDescription" => "Automatic fan control",
        "Settings" => "Settings",
        "CheckUpdates" => "Check for updates",
        "OpenLog" => "Open log",
        "Exit" => "Exit",
        "ModeError" => "Could not switch mode",
        "FanError" => "Could not switch fan mode",
        "PartialMode" => "Mode was applied partially. See the log for details",
        "General" => "General",
        "Power" => "Power",
        "About" => "About",
        "GeneralTitle" => "General",
        "GeneralSubtitle" => "Modes, the hardware button, shortcut, and notifications",
        "QuickControls" => "Quick controls",
        "CurrentMode" => "Current mode",
        "ChangingMode" => "Applying mode...",
        "ChangingFan" => "Applying fan mode...",
        "ModeApplied" => "Mode applied",
        "FanDescription" => "Independently enables the maximum fan speed",
        "Language" => "App language",
        "LanguageSystem" => "Use Windows language",
        "LanguageDescription" => "The Windows display language is used by default",
        "Notifications" => "Switch notifications",
        "NotificationsDescription" => "Show a compact toast when the diamond button or shortcut is used",
        "KeyboardShortcut" => "Keyboard shortcut",
        "KeyboardShortcutDescription" => "Mirrors 1, 2, or 3 diamond-button presses",
        "ShortcutNotAssigned" => "Not assigned",
        "RecordShortcut" => "Record shortcut",
        "PressShortcut" => "Press a shortcut...",
        "ShortcutNeedsModifier" => "Add Ctrl / Alt / Shift / Win",
        "ClearShortcut" => "Remove shortcut",
        "ShortcutConflict" => "This shortcut is already used by Windows or another app. The previous shortcut was kept.",
        "ShortcutRegistrationFailed" => "Windows could not register the shortcut (error {0}). The previous shortcut was kept.",
        "ShortcutStartupFailed" => "The configured shortcut is in use and is currently unavailable. Choose another one in Settings.",
        "DiamondButton" => "Diamond button and shortcut",
        "DiamondDescription" => "Gestures are recognized from quick consecutive presses",
        "SinglePress" => "One press",
        "DoublePress" => "Two presses",
        "TriplePress" => "Three presses",
        "ToggleModes" => "Standard ↔ Performance",
        "ToggleMaxFan" => "Toggle Max Fan",
        "EnableEco" => "Enable Eco",
        "PowerTitle" => "Power and Eco",
        "PowerSubtitle" => "Fine-grained power-saving controls",
        "EcoBehaviorTitle" => "Eco behavior",
        "EcoRefreshRate" => "Limit display to 60 Hz",
        "EcoRefreshRateDescription" => "Built-in display only; its original refresh rate is restored after Eco",
        "EcoFrameRate" => "Limit NVIDIA to 60 FPS",
        "EcoFrameRateDescription" => "Global driver limit; a lower existing limit is preserved",
        "EcoTurboBoost" => "Disable Turbo Boost",
        "EcoTurboBoostDescription" => "Reduces peak processor power and heat",
        "WindowsPowerTitle" => "Windows tuning",
        "ApplyingEcoBehavior" => "Applying Eco settings...",
        "EcoBehaviorApplied" => "Eco settings applied",
        "PowerTuning" => "Tune Windows together with the mode",
        "PowerTuningDescription" => "Tunes Windows for speed in Performance and efficiency in Eco",
        "EcoAcLimit" => "Eco CPU limit on AC",
        "EcoAcDescription" => "Maximum processor performance while plugged in",
        "EcoBatteryLimit" => "Eco CPU limit on battery",
        "EcoBatteryDescription" => "Maximum processor performance without the charger",
        "PowerRestoreNote" => "Eco-only values return after Eco; Windows tuning returns in Standard.",
        "AboutTitle" => "Victus Mode Switch",
        "AboutSubtitle" => "A lightweight mode controller for supported HP Victus laptops",
        "Version" => "Version {0}",
        "SupportedHardware" => "Supported device",
        "SupportedHardwareDescription" => "HP Victus 15-fa0020ua, system board 8A4F, Thermal Policy V0",
        "Updates" => "Updates",
        "CheckForUpdates" => "Check for updates automatically",
        "CheckForUpdatesDescription" => "GitHub Releases is checked no more than once per day",
        "CheckNow" => "Check now",
        "CheckingUpdate" => "Checking GitHub Releases...",
        "UpToDate" => "You have the latest version",
        "UpdateAvailable" => "Version {0} is available",
        "UpdateError" => "Could not check for updates",
        "OpenGitHub" => "Open project on GitHub",
        "BuiltWithAi" => "This project was developed with AI assistance and tested on one laptop.",
        "RiskNoticeTitle" => "Use at your own risk",
        "RiskNotice" => "The app calls an undocumented HP BIOS interface. The author and contributors accept no liability for damage, data loss, or warranty consequences.",
        "UpdateReadyTitle" => "Update available",
        "UpdateReadyDescription" => "Victus Mode Switch {0} is ready to install.",
        "ReleaseNotes" => "What's new",
        "InstallUpdate" => "Download and install",
        "Later" => "Later",
        "DownloadingUpdate" => "Downloading installer... {0}%",
        "VerifyingUpdate" => "Verifying SHA-256...",
        "UpdateFailed" => "Update was not installed: {0}",
        _ => key
    };
}

internal sealed record LanguageOption(string Code, string Name);
